# Generated by Django 4.1.7 on 2023-02-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/')),
                ('thumbnail_200', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('thumbnail_400', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('original_link', models.URLField(blank=True, null=True)),
                ('expiring_link', models.URLField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
